# Generated by Django 4.1.3 on 2022-11-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Endereco_Entrega',
            new_name='ShippingAddress',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='transacao_id',
            new_name='transaction_id',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='data_added',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='date_time',
            new_name='date_added',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
